test:
	$(MAKE) -C initvelocity_evaluation && \
	$(MAKE) -C randomnumbergenerators_evaluation && \
	$(MAKE) -C positionandvelocityupdater_evaluation && \
	$(MAKE) -C boundhandling_velocityadjustment_evaluation && \
	$(MAKE) -C neighborhood_evaluation && \
	$(MAKE) -C function_evaluation && \
	$(MAKE) -C statistic_evaluation
