CFLAGS=-Wall -std=c++11
OPTIMIZATION=-O5
LDFLAGS=-lgmp
DEBUGFLAG=

INCLUDE_FILE=general/includes.h

SOURCES=$(filter-out general/main.cpp, $(wildcard bound_handling/*.cpp) $(wildcard function/*.cpp) $(wildcard position_and_velocity_updater/*.cpp) $(wildcard neighborhood/*.cpp) $(wildcard velocity_adjustment/*.cpp) $(wildcard statistics/*.cpp) $(wildcard general/*.cpp))

OBJECTS=$(addprefix $(BUILD_DIR)/, $(SOURCES:.cpp=.o))
H_FILES=$(SOURCES:.cpp=.h)

EXECUTABLE=high_precision_pso
TEST_PROGRAM=test_program
BUILD_DIR=build


all: $(EXECUTABLE)
	
$(EXECUTABLE): $(INCLUDE_FILE) $(OBJECTS) $(BUILD_DIR)/general/main.o
	$(CXX) $(OBJECTS) $(BUILD_DIR)/general/main.o $(LDFLAGS) -o $@

$(TEST_PROGRAM): $(INCLUDE_FILE) $(OBJECTS) $(BUILD_DIR)/testing/tests.o
	$(CXX) $(OBJECTS) $(BUILD_DIR)/testing/tests.o $(LDFLAGS) -o $@

$(INCLUDE_FILE): $(H_FILES)
	echo "/**" > $@&& \
	echo "* @file   $@" | sed "s#general/##" >> $@&& \
	echo "* @author automatically generated by makefile" >> $@ && \
	LANG=en_EN.utf8 date "+* @date   %B, %Y" >> $@ && \
	echo "* @brief  This file enforces all .h files to be included." >> $@ && \
	echo "*" >> $@ && \
	echo "* @copyright" >> $@ && \
	echo "* This project is released under the MIT License (MIT)." >> $@ && \
	echo "*" >> $@ && \
	echo "* @copyright" >> $@ && \
	echo "* The MIT License (MIT)" >> $@ && \
	echo "*" >> $@ && \
	echo "* @copyright" >> $@ && \
	echo "* Copyright (c) 2016 by Friedrich-Alexander-Universität Erlangen-Nürnberg" >> $@ && \
	echo "*" >> $@ && \
	echo "* @copyright" >> $@ && \
	echo "* Permission is hereby granted, free of charge, to any person obtaining a copy" >> $@ && \
	echo "* of this software and associated documentation files (the \"Software\"), to deal" >> $@ && \
	echo "* in the Software without restriction, including without limitation the rights" >> $@ && \
	echo "* to use, copy, modify, merge, publish, distribute, sublicense, and/or sell" >> $@ && \
	echo "* copies of the Software, and to permit persons to whom the Software is" >> $@ && \
	echo "* furnished to do so, subject to the following conditions:" >> $@ && \
	echo "*" >> $@ && \
	echo "* @copyright" >> $@ && \
	echo "* The above copyright notice and this permission notice shall be included in" >> $@ && \
	echo "* all copies or substantial portions of the Software." >> $@ && \
	echo "*" >> $@ && \
	echo "* @copyright" >> $@ && \
	echo "* THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR" >> $@ && \
	echo "* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY," >> $@ && \
	echo "* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE" >> $@ && \
	echo "* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER" >> $@ && \
	echo "* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM," >> $@ && \
	echo "* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE" >> $@ && \
	echo "* SOFTWARE." >> $@ && \
	echo "*" >> $@ && \
	echo "*/" >> $@ && \
	echo "" >> $@ && \
	echo $(H_FILES) | tr ' ' '\n' | grep -v "check_condition.h" | sed "s:$$:\":" | sed "s:^:#include \":" | sort >> $@

test: $(TEST_PROGRAM) $(EXECUTABLE)
	./$(TEST_PROGRAM) && \
	$(MAKE) -C testing/test_data_sets/


$(BUILD_DIR)/%.o : %.cpp
	mkdir -p $(addprefix $(BUILD_DIR)/, $(dir $*))
	$(CXX) -I . -MT $@ -MMD -MP -MF $(BUILD_DIR)/$*.temp.d $(CFLAGS) $(DEBUGFLAG) $(OPTIMIZATION) -c -o $(BUILD_DIR)/$*.o $*.cpp
	mv -f $(BUILD_DIR)/$*.temp.d $(BUILD_DIR)/$*.d

$(BUILD_DIR)/%.d: ;

.PRECIOUS: $(BUILD_DIR)/%.d

-include $(OBJECTS:.o=.d)

clean:
	rm -rf $(BUILD_DIR) $(EXECUTABLE) $(INCLUDE_FILE) $(TEST_PROGRAM)

debug:
	make all "OPTIMIZATION=-O0" "DEBUGFLAG=-g"

debugtest:
	make test "OPTIMIZATION=-O0" "DEBUGFLAG=-g"

.PHONY: doc

doc:
	doxygen doc/doxygen.conf > /dev/null

cleandoc:
	rm -rf doc/html

